
##### RESOURCES #####
# memory (mem) in MB
mem: '4000'
threads: 1

##### GENERAL #####
project_name: myData
email: arya-zandvakili@uiowa.edu # used for UCSC hub generation

##### PROCESSING #####
# genome label for UCSC hub (hg38, mm10) and IGV-report
genomes: 
    cmv: 
        genbank: "KF297339.1"

##### VISUALIZATION using gtracks powered by pyGenomeTracks #####

# position of x-axis
x_axis: 'bottom'

#  width of plot in cm (default: 40)
width: 20

# how many bases up- & downstream of start/end of a gene more to plot (e.g., to see accessible promoters)
base_buffer: 2000

# file type of the plot, options are "svg","pdf","png"
file_type: "pdf"

# define custom colors (in HEX) for groups from the annotation file
track_colors:
    untreated: "#800080"
    treated: "#00FFFF"
