# always use absolute paths

##### RESOURCES #####
# memory in MB
partition: 'tinyq'
mem: '4000'
threads: 1

##### GENERAL #####
project_name: INT
result_path: /nobackup/lab_bock/projects/bmdm-stim/results/INT/
sample_annotation: /nobackup/lab_bock/projects/bmdm-stim/results/metadata/genome_tracks_annotation_new.csv
gene_list: /research/home/sreichl/projects/bmdm-stim/metadata/genome_tracks_genes_reduced.txt
genome_bed: /nobackup/lab_bock/projects/bmdm-stim/resources/mm10_UCSC_genome.bed.gz

### for bigWig generation using bamCoverage ###
genome_size: 2407883318
# hg38: 2747877777
# mm10: 2407883318


##### VISUALIZATION using gtracks #####
# y axis scale if '' it uses auto-scale for each track
y_max: 100
# position of x-axis
x_axis: 'bottom'
#  width of plot in cm (default: 40)
width: 20
# how many bases up- & downstream more to plot (eg to see accessible promoters)
base_buffer: 2000

